// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlo4FuoR83BJJIP2Zv4xgfJpTCF7ZrdSs',
    appId: '1:700518376829:web:523eeec0e71039f509d814',
    messagingSenderId: '700518376829',
    projectId: 'eventmanager-14d4b',
    authDomain: 'eventmanager-14d4b.firebaseapp.com',
    storageBucket: 'eventmanager-14d4b.appspot.com',
    measurementId: 'G-ECT73RFRBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWgu-cqwgArmxMdZdrS2ZWk8P9TB41L38',
    appId: '1:700518376829:android:a1d8fe339afeeae109d814',
    messagingSenderId: '700518376829',
    projectId: 'eventmanager-14d4b',
    storageBucket: 'eventmanager-14d4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7xpLGDW1_MidvMRoAYYrHw_4bGjBXfDs',
    appId: '1:700518376829:ios:40d1f0c12e47394009d814',
    messagingSenderId: '700518376829',
    projectId: 'eventmanager-14d4b',
    storageBucket: 'eventmanager-14d4b.appspot.com',
    iosClientId: '700518376829-k5df09gkho8dj5k8oh2jbgd768ca5t97.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventmanager',
  );
}
